# NumPy  
  
Es una librería para trabajar con vectores y matrices multidimensionales, con una colección de funciones matemáticas
poderosas.  
  
Su estructura de datos fundamental es *ndarray* que permite configurar una matriz de *n* dimensiones. La matriz debe ser homogénea.

## Instalación

pip install numpy

## Creación de un ndarray

np.array(*secuencia*)

In [3]:
import numpy as np
# vec=np.array([2,4,8,3])
# print(vec)
# print(type(vec))
# print(vec.dtype) # tipo de dato que almacena el array
vec=np.array([1.2,3,5.4])
print(vec)
print(vec.dtype)

[1.2 3.  5.4]
float64


In [4]:
# En un array de np todos los elementos deben ser del mismo tipo. Y si no, se convierten a un tipo común
vec2=np.array([15,"casa", 33, 1.2, True, 1+5j])
print(vec2)
print(vec2.dtype)

['15' 'casa' '33' '1.2' 'True' '(1+5j)']
<U64


Transforma secuencias de secuencias en un array de 2 dimensiones, secuencias de secuencias de secuencias en uno de 3 y así sucesivamente:

In [6]:
import numpy as np
dosD=np.array([[1,4,2], [4,5,3]])
print(dosD)
print("---")
tresD=np.array((((1,2),(4,3),(5,3)),((8,9),(2,6),(2,1))))
print(tresD)

[[1 4 2]
 [4 5 3]]
---
[[[1 2]
  [4 3]
  [5 3]]

 [[8 9]
  [2 6]
  [2 1]]]


Podemos declarar el tipo en su constructor:

In [7]:
import numpy as np
entero=np.array([1,5,2,3], dtype="int32")
print(entero)
flotante=np.array([1,5,2,3], dtype="float64")
print(flotante)
complejo=np.array([1,5,2,3], dtype="complex")
print(complejo)
alreves=np.array([1.3, 2.4, 5.5], dtype="int32")
print(alreves)

[1 5 2 3]
[1. 5. 2. 3.]
[1.+0.j 5.+0.j 2.+0.j 3.+0.j]
[1 2 5]


Y si ya tenía las listas, con lo cual puedo hacer un array usando una lista, una matriz 2D usando una lista de listas, y así sucesivamente, ¿para qué tengo numpy? Porque tengo unas operaciones impresionantes!

In [48]:
import numpy as np
vector=np.random.randint(1, 100, 10) #Generación de arrays con valores aleatorios randint(numini, numfin, cantidad)
vector2=np.random.randint(1, 100, 10)
print(vector.shape)

print(f"Vector: {vector}")
print(f"Vector2: {vector2}")
print(f"Vector con elementos duplicados: {vector*2}")
print(f"Suma de los elementos de Vector: {np.sum(vector)}")
print(f"Media del Vector: {np.mean(vector)}")
print(f"Suma de vectores: {vector+vector2}")
print(f"Un slice: {vector2[3:6]}")

(10,)
Vector: [66 98 84 89 96 57 52 36 46 60]
Vector2: [98 83 91 14 28 67 17  2 47 37]
Vector con elementos duplicados: [132 196 168 178 192 114 104  72  92 120]
Suma de los elementos de Vector: 684
Media del Vector: 68.4
Suma de vectores: [164 181 175 103 124 124  69  38  93  97]
Un slice: [14 28 67]


El manejo de los slices del vector se realiza de la misma manera que con las secuencias *[inicio:fin]*

## Matrices

Las puedo crear con listas de listas, o listas de listas de listas, y así sucesivamente según la cantidad de dimensiones. En los métodos donde se genera automáticamente la matriz, en el parámetro de tamaño paso una tupla con las dimensiones.

In [28]:
import numpy as np
dimensiones=(5,4)
matrizale=np.random.randint(1, 100, dimensiones) #Generación de matriz con valores aleatorios
matrizDe1=np.ones(dimensiones) # Generación con unos.
matrizDe0=np.zeros(dimensiones) # Generación con ceros
print(matrizale)
print("---")
# print(matrizDe1)
# print("---")
# print(matrizDe0)
# print("----")
# print(matrizDe1-0.5)
print(matrizale/2)

[[75 24 36 15]
 [78 95 39 53]
 [ 1 12 98 38]
 [16 84 60 24]
 [17 81 66 21]]
---
[[37.5 12.  18.   7.5]
 [39.  47.5 19.5 26.5]
 [ 0.5  6.  49.  19. ]
 [ 8.  42.  30.  12. ]
 [ 8.5 40.5 33.  10.5]]


Ahora puedo utilizar los slices para acceder a sus elementos, pero considerando que tenemos 2 dimensiones, vamos a tener dos rangos, el primero para las filas y el segundo para las columnas. Así aumentaríamos los rangos según la cantidad de dimensiones que maneje.

In [39]:
import numpy as np
dimensiones=(5,4)
matriz=np.random.randint(1, 100, dimensiones) #Generación de matriz con valores aleatorios
print(matriz)
print("---")
print(matriz[3,2]) # Un elemento en la posición deseada de la matriz
print("---")
print(matriz[1,:]) # Fila 1 de la matriz
print("---")
print(matriz[:, 3]) # Columna 3 de la matriz
print("---")
print(matriz[0:2, 0:2]) # Submatriz de 2x2 de la esquina superior izquierda

[[47 31  7 55]
 [76 88 17 81]
 [79 79 40 91]
 [98 21 52 23]
 [ 5 67 50 67]]
---
[[47 31]
 [76 88]]


In [44]:
matriz=np.random.randint(1, 100, (15,10))
print(matriz)
# matriz[2,:]=0
matriz[3:6, 4:8]*=100
print("----")

print(matriz)

[[37 32 86 49 11 24 51 86 33 41]
 [73 52 49 31 28 63 91 44 30 69]
 [43 80 59 69 49 27  3 43 40 53]
 [47 11 65 32 48 80 57 54 56 74]
 [57 30 94 67 37 69 97 35  5 45]
 [85 49  2 92 26 84 97 34 99 47]
 [51 35 39 70 74 73 71 92 72  8]
 [ 5 22 99 26 32 80 20 74 56 78]
 [87  3 43 54 26  3 45  1 94 47]
 [90 74 43 92 18 25 74  4 36 63]
 [23 50 15 68 91 48 84  6 80 61]
 [48  7  5 71 61 52 60  1 58 85]
 [ 1 85 80 23 89 77 37 32 92 29]
 [41 22 64 24 47 38 53 56 44 87]
 [32 43 21 74 51 57 81 36 94 82]]
----
[[  37   32   86   49   11   24   51   86   33   41]
 [  73   52   49   31   28   63   91   44   30   69]
 [  43   80   59   69   49   27    3   43   40   53]
 [  47   11   65   32 4800 8000 5700 5400   56   74]
 [  57   30   94   67 3700 6900 9700 3500    5   45]
 [  85   49    2   92 2600 8400 9700 3400   99   47]
 [  51   35   39   70   74   73   71   92   72    8]
 [   5   22   99   26   32   80   20   74   56   78]
 [  87    3   43   54   26    3   45    1   94   47]
 [  90   74   43   92 

In [47]:
#Operaciones con matrices
import numpy as np
dimensiones=(5,4)
matriz=np.random.randint(1, 100, dimensiones) #Generación de matriz con valores aleatorios
print(matriz.shape)
print(matriz)
print("---")
matriz[:,1]=matriz[:,1]*2 #Multiplico por 2 la segunda columna
print(matriz)
print("---")
matriz[3:]=matriz[4:] #Copio la fila 4 en la 3
print(matriz)
print("---")

(5, 4)
[[83 46 70 26]
 [88 43 24 93]
 [69 97 49 65]
 [42 59 99 58]
 [73 14 43 55]]
---
[[ 83  92  70  26]
 [ 88  86  24  93]
 [ 69 194  49  65]
 [ 42 118  99  58]
 [ 73  28  43  55]]
---
[[ 83  92  70  26]
 [ 88  86  24  93]
 [ 69 194  49  65]
 [ 73  28  43  55]
 [ 73  28  43  55]]
---


## Numpy y las imágenes

Dado que una imagen no es más que una matriz numérica, donde los números representan sus píxeles, numpy nos dejará operar sobre la imagen realizando diversos tipos de procedimiento sobre sus valores

Para poder mostrar la imagen en pantalla y realizar ciertas operaciones, usaremos el módulo ***OpenCV***. Ver cómo instalarlo!

<center><img src="images/chalten.jpg" alt="Chalten" title="Imagen que vamos a procesar" /></center><br>

pip install opencv-python


In [2]:
import cv2
img=cv2.imread("images/chalten.jpg") # Abrir un archivo con una imagen
# ¿Qué quedó en img?
print(type(img))
print("¡SIII, un array de numpy!")
print("Dimensiones de la imagen: {}", img.shape) # La última dimensión es el valor de los colores
print(img[-1,-1])
print(img[682,1023])
cv2.imshow('Chalten', img) # Muestra img en una ventana
cv2.waitKey(0) # espera una tecla para salir
cv2.destroyAllWindows() # Destruye todas las ventanas creadas (si no se va a colgar el kernel!)

<class 'numpy.ndarray'>
¡SIII, un array de numpy!
Dimensiones de la imagen: {} (683, 1024, 3)
[97 91 92]
[97 91 92]


In [7]:
# Y ahora a empezar a jugar!!!
import cv2
img=cv2.imread("images/chalten.jpg")
img[:,:,0]=0 # 0:Blue, 1:Green, 2:Red
img[:,:,1]=0
cv2.imshow('Chalten', img)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [8]:
import cv2
img=cv2.imread("images/chalten.jpg")
img[:,:,0]=255-img[:,:,0] # 0:Blue, 1:Green, 2:Red
img[:,:,1]=255-img[:,:,1]
img[:,:,2]=255-img[:,:,2]
cv2.imshow('Chalten', img)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [10]:
import cv2
img=cv2.imread("images/chalten.jpg")
imgNeg=255-img #Negativo!!
imgNegNeg=255-imgNeg #Negativo del negativo
cv2.imshow('ChaltenNeg', imgNeg)
cv2.imshow('ChaltenNegNeg', imgNegNeg)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [ ]:
import cv2
img=cv2.imread("images/chalten.jpg")
img2=img[0:300, 0:250] #Tomo una parte de la imagen
cv2.imshow('Chalten', img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [16]:
import cv2
import numpy as np
img=cv2.imread("images/chalten.jpg")
img2=np.flip(img, 1) # Flipeamos la matriz
cv2.imshow('Chalten', img) 
cv2.imshow('Chalten Invertido', img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [17]:
img=cv2.imread("images/chalten.jpg")
img[:341]=img[342:] #Copio la parte de abajo en la de arriba
cv2.imshow('Chalten', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img=cv2.imread("images/chalten.jpg")
img[:,0:512]=img[:,512:] #Copio la parte derecha en la izquierda
cv2.imshow('Chalten', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
#Algunas funciones de OpenCV
import cv2
import numpy as np
img=cv2.imread("images/chalten.jpg")
img2=cv2.medianBlur(img, 5)
img3=cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE) # El segundo parámetro es una constante que me indica cómo rotar
img4=np.rot90(img,2) # El segundo parámetro me indica la cantidad de rotaciones a aplicar
cv2.imshow('Chalten', img) 
cv2.imshow('Chalten Borroso', img2) 
cv2.imshow('Chalten Rotado', img3) 
cv2.imshow('Chalten Rotado por numpy', img4) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [22]:
# Conversión de color 
# https://docs.opencv.org/3.4/d8/d01/group__imgproc__color__conversions.html#ga4e0972be5de079fed4e3a10e24ef5ef0
import cv2
import numpy as np
img=cv2.imread("images/chalten.jpg")
img2=cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
cv2.imshow('Chalten en gris', img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [23]:
# Detección de bordes
# cv2.Canny(imagen, minval, maxval)
# Primero calcula los gradientes (cuánto cambia el valor del pixel con respecto a sus vecinos)
# Luego considera sí o sí bordes los que superan el maxval, y no los que están por debajo de minval. Para lo que queda en el medio
# analiza la continuidad con otro borde
import cv2
import numpy as np
img=cv2.imread("images/chalten.jpg")
img2=cv2.Canny(img, 100, 200)
cv2.imshow('Bordes detectados', img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

## Captura de cámara
Es exactamente lo mismo, capturando cuadro a cuadro el video


In [ ]:
import cv2
import numpy as np
cam=cv2.VideoCapture(0) #Qué camara voy a capturar?
while(True):
    ret, cuadro=cam.read()
    if ret:
#         nueva=cv2.cvtColor(cuadro, cv2.COLOR_RGB2GRAY)
#         cuadro[:,:,0]=0
#         cuadro[:,:,1]=0
        nueva=np.rot90(cuadro,1)
#         nueva=cv2.Canny(cuadro, 100, 200)
#         nueva=cv2.medianBlur(cuadro, 5)
        cv2.imshow("Nueva", nueva)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
cam=cv2.VideoCapture(0) #Qué camara voy a capturar?
while(True):
    ret, img=cam.read()
    if ret:
        alto_medio = int(img.shape[0]/2)
        img[:alto_medio,:,0]=0 # 0:Blue, 1:Green, 2:Red
        img[:alto_medio,:,1]=0 # 0:Blue, 1:Green, 2:Red
        img[alto_medio:,:,0]=0
        img[alto_medio:,:,2]=0
        cv2.imshow("Color", img)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
cam.release()
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np
cam=cv2.VideoCapture(0)
while(True):
    ret, img=cam.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 5)
    edges = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 9, 9)
    color = cv2.bilateralFilter(img, 9, 300, 300)
    cartoon = cv2.bitwise_and(color, color, mask=edges)
    cv2.imshow("Cartoon", cartoon)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cam.release()
cv2.destroyAllWindows()
